import { TourStep } from '@/store/tourStore';
import { router } from 'expo-router';

export const invoicesTourSteps: TourStep[] = [
  {
    id: 'invoices-overview',
    title: 'Welcome to Invoice Management',
    text: 'This is your invoice dashboard where you can view, search, and manage all your invoices. Let me show you around!',
    placement: 'center',
  },
  {
    id: 'add-invoice-button',
    title: 'Create New Invoice',
    text: 'Tap this blue + button to create a new invoice. This is your starting point for billing customers.',
    highlight: { x: 330, y: 80, width: 44, height: 44 },
    placement: 'left',
    pulseTarget: true,
  },
  {
    id: 'search-functionality',
    title: 'Search Your Invoices',
    text: 'Use this search bar to quickly find invoices by number, customer name, or email address.',
    highlight: { x: 20, y: 140, width: 280, height: 48 },
    placement: 'bottom',
    pulseTarget: true,
  },
  {
    id: 'filter-options',
    title: 'Filter by Status',
    text: 'These buttons help you filter invoices by status - All, Draft, Sent, Paid, or Overdue. Very handy for organization!',
    highlight: { x: 20, y: 200, width: 350, height: 40 },
    placement: 'bottom',
    pulseTarget: true,
  },
  {
    id: 'invoice-cards',
    title: 'Your Invoice Cards',
    text: 'Each invoice appears as a card showing customer info, amount, status, and due date. Tap the action buttons to view, edit, or delete.',
    highlight: { x: 20, y: 260, width: 350, height: 140 },
    placement: 'bottom',
    pulseTarget: true,
  },
  {
    id: 'navigate-create',
    title: 'Ready to Create?',
    text: 'Now let\'s create your first invoice! I\'ll guide you through every step of the process.',
    placement: 'center',
    buttonText: 'Let\'s Create!',
    action: () => {
      setTimeout(() => {
        router.push('/(tabs)/create');
      }, 500);
    },
  },
];

export const createTourSteps: TourStep[] = [
  {
    id: 'create-welcome',
    title: 'Invoice Creation Wizard',
    text: 'Welcome to invoice creation! I\'ll guide you through each section step-by-step. Let\'s build your first professional invoice together.',
    placement: 'center',
    buttonText: 'Let\'s Start!',
  },
  {
    id: 'customer-name-input',
    title: 'Customer Name (Required)',
    text: 'Start with your customer\'s name. This is required and will appear prominently on the invoice.',
    highlight: { x: 20, y: 180, width: 350, height: 48 },
    placement: 'bottom',
    pulseTarget: true,
    buttonText: 'Got it!',
    skipable: true,
  },
  {
    id: 'customer-email-input',
    title: 'Customer Email (Required)',
    text: 'Enter the customer\'s email address. This is essential for sending the invoice electronically.',
    highlight: { x: 20, y: 240, width: 350, height: 48 },
    placement: 'bottom',
    pulseTarget: true,
    buttonText: 'Next Field',
  },
  {
    id: 'customer-phone-input',
    title: 'Phone Number (Optional)',
    text: 'Add the customer\'s phone number for additional contact information. This is optional but recommended.',
    highlight: { x: 20, y: 300, width: 350, height: 48 },
    placement: 'bottom',
    pulseTarget: true,
    buttonText: 'Continue',
  },
  {
    id: 'customer-address-input',
    title: 'Billing Address (Optional)',
    text: 'Enter the customer\'s billing address. This will appear on the invoice for professional presentation.',
    highlight: { x: 20, y: 360, width: 350, height: 80 },
    placement: 'bottom',
    pulseTarget: true,
    buttonText: 'Next Section',
  },
  // {
  //   id: 'invoice-items-header',
  //   title: 'Invoice Items Section',
  //   text: 'Now for the important part - adding items to your invoice! Each item represents a product or service you\'re billing for.',
  //   highlight: { x: 20, y: 480, width: 350, height: 60 },
  //   placement: 'bottom',
  //   buttonText: 'Show Me Items',
  // },
  // {
  //   id: 'add-item-button',
  //   title: 'Add More Items',
  //   text: 'Use this green + button to add additional line items to your invoice. You can add as many as needed!',
  //   highlight: { x: 334, y: 500, width: 36, height: 36 },
  //   placement: 'left',
  //   pulseTarget: true,
  //   buttonText: 'Understood',
  // },
  // {
  //   id: 'item-description',
  //   title: 'Item Description (Required)',
  //   text: 'Describe what you\'re billing for. Be specific and clear so your customer understands exactly what they\'re paying for.',
  //   highlight: { x: 40, y: 600, width: 310, height: 48 },
  //   placement: 'bottom',
  //   pulseTarget: true,
  //   buttonText: 'Next Field',
  // },
  // {
  //   id: 'item-quantity',
  //   title: 'Quantity',
  //   text: 'Enter how many units you\'re billing for - this could be hours, pieces, licenses, etc.',
  //   highlight: { x: 40, y: 680, width: 95, height: 48 },
  //   placement: 'bottom',
  //   pulseTarget: true,
  //   buttonText: 'Next Field',
  // },
  // {
  //   id: 'item-rate',
  //   title: 'Rate per Unit',
  //   text: 'Enter your price per unit. This will be multiplied by quantity to calculate the line total automatically.',
  //   highlight: { x: 147, y: 680, width: 95, height: 48 },
  //   placement: 'bottom',
  //   pulseTarget: true,
  //   buttonText: 'See Calculation',
  // },
  // {
  //   id: 'item-amount',
  //   title: 'Auto-Calculated Amount',
  //   text: 'The total for this line item is calculated automatically (Quantity × Rate). No math required!',
  //   highlight: { x: 254, y: 680, width: 95, height: 48 },
  //   placement: 'left',
  //   pulseTarget: true,
  //   buttonText: 'Amazing!',
  // },
  // {
  //   id: 'remove-item-feature',
  //   title: 'Remove Items',
  //   text: 'Need to remove an item? Just tap this red trash icon. Note: You must have at least one item on every invoice.',
  //   highlight: { x: 350, y: 560, width: 24, height: 24 },
  //   placement: 'left',
  //   pulseTarget: true,
  //   buttonText: 'Good to Know',
  // },
  // {
  //   id: 'due-date-field',
  //   title: 'Payment Due Date',
  //   text: 'Set when payment is due. Use YYYY-MM-DD format, or leave blank to default to 30 days from today.',
  //   highlight: { x: 20, y: 820, width: 350, height: 48 },
  //   placement: 'top',
  //   pulseTarget: true,
  //   buttonText: 'Next Field',
  // },
  // {
  //   id: 'notes-field',
  //   title: 'Additional Notes',
  //   text: 'Add payment terms, special instructions, or thank you messages. This appears at the bottom of your invoice.',
  //   highlight: { x: 20, y: 880, width: 350, height: 80 },
  //   placement: 'top',
  //   pulseTarget: true,
  //   buttonText: 'Almost Done!',
  // },
  // {
  //   id: 'invoice-summary-section',
  //   title: 'Invoice Summary',
  //   text: 'Review your totals here. The system automatically calculates subtotal, adds 10% tax, and shows the final total.',
  //   highlight: { x: 20, y: 1000, width: 350, height: 120 },
  //   placement: 'top',
  //   pulseTarget: true,
  //   buttonText: 'Perfect!',
  // },
  // {
  //   id: 'save-draft-action',
  //   title: 'Save as Draft',
  //   text: 'Save your invoice as a draft to continue editing later. Drafts won\'t be sent to customers until you\'re ready.',
  //   highlight: { x: 20, y: 1150, width: 165, height: 48 },
  //   placement: 'top',
  //   pulseTarget: true,
  //   buttonText: 'Got it',
  // },
  // {
  //   id: 'send-invoice-action',
  //   title: 'Send Invoice',
  //   text: 'Ready to bill? This sends the completed invoice to your customer and changes the status to "Sent".',
  //   highlight: { x: 197, y: 1150, width: 165, height: 48 },
  //   placement: 'top',
  //   pulseTarget: true,
  //   buttonText: 'Excellent!',
  // },
  // {
  //   id: 'creation-complete',
  //   title: 'You\'re Ready to Invoice! 🎉',
  //   text: 'Congratulations! You now know how to create professional invoices. Fill out the form and create your first invoice!',
  //   placement: 'center',
  //   buttonText: 'Start Invoicing!',
  //   skipable: false,
  // },
];